export enum PosicionJugador {
    ARQUERO = 1,
    DEFENSOR_CENTRAL,
    LATERAL_IZQUIERDO,
    LATERAL_DERECHO,
    MEDIO_CENTRO,
    MEDIO_CENTRO_DEFENSIVO,
    MEDIO_CENTRO_OFENSIVO,
    MEDIO_IZQUIERDO,
    MEDIO_DERECHO,
    EXTREMO_IZQUIERDO,
    EXTREMO_DERECHO,
    DELANTERO_CENTRO
}
